### PR TITLE
Downgrade OTP to 20.0.5

### PR DESCRIPTION
**Pull request by asridharan**
Due to the `hostname` check validation errors for x509 certificates downgrading OTP version to 20.0.5.

---
This change is [Reviewable](https://reviewable.io/reviews/dcos/dcos-net/29)

### CODE REVIEW

**Comment by urbanserj** [comment]
We don’t need to downgrade anything in dcos-net repository, we should downgrade only erlang package in dcos/dcos repo.

**Comment by asridharan** [comment]
@urbanserj the ref in `dcos/dcos` repo points to the head of `dcos-net` at this point. However, there are quite a few commits between the head and the commit introducing the OTP upgrade. We need all those commits. Hence, explicitly reverted the upgrade while keeping all the commits.

**Comment by asridharan** [comment]
Ah !! I misunderstood. Didn't realize we have an explicit package for OTP in DC/OS:
https://github.com/dcos/dcos/blob/master/packages/erlang/buildinfo.json

Will look at just downgrading the OTP package.

**Comment by gabrielhartmann** [comment]
Is there another PR I should be watching?

**Comment by asridharan** [comment]
@gabrielhartmann will close this out. @urbanserj was able to reproduce the problem and should have a fix shortly. Will update the JIRA with the PRs.

**Comment by gabrielhartmann** [comment]
Cool, thanks.

**Pull request closed without merging**
